title: Bark Life
subtitle: Halifax Dog Walking
email: barklifehfx@gmail.com
phone: 1-902-888-8888
description: >
  Halifax dog walking opportunities.
  
###
### Probably shouldn't edit the settings below
###

google_analytics: UA-73887811-7

baseurl: ""
url: ""

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default

markdown: kramdown
#theme: minima

exclude: [
  'gulpfile.js',
  'package.json',
  'node_modules'
  ]

