title: Bark Life
subtitle: Halifax Dog Walking
email: barklifehfx@gmail.com
phone: 1-902-292-3647
description: >
  Halifax dog walking opportunities.
  
###
### Probably shouldn't edit the settings below
###

baseurl: "https://bozdoz.github.io/barklifehfx/"
url: ""

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default

google_fonts : Neucha|Poppins:300
google_maps_api : AIzaSyCC5RojknjT5x7CyLpO-OV33UrF-6nKtao
google_analytics : UA-73887811-7

markdown: kramdown
exclude: [
  'gulpfile.js',
  'package.json',
  'node_modules'
  ]
