title: Bark Life
subtitle: Halifax Dog Walking
email: barklifehfx@gmail.com
phone: 1-902-888-8888
description: > # this means to ignore newlines until "baseurl:"
  Halifax dog walking opportunities.

###
### Probably shouldn't edit the settings below
###

baseurl: ""
url: ""

markdown: kramdown
#theme: minima

exclude: [
  'gulpfile.js',
  'package.json',
  'node_modules'
  ]